image: docker:latest
services:
  - docker:18.09.6-dind
stages:
  - package
  - deploy
  - backend
variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: "tcp://localhost:2375"
  REPOSITORY_IMAGE: "${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_PIPELINE_IID}"
  REPOSITORY_IMAGE_BACKEND: "${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_PIPELINE_IID}-backend"

package:
  tags:
    - kuber
  stage: package
  only:
    - develop
    - master
  image: docker:18.09.6-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN ${CI_REGISTRY}
    - docker build -f Dockerfile --network=host -t ${REPOSITORY_IMAGE} .
    - docker push ${REPOSITORY_IMAGE}
    - docker build -f Dockerfile.node --network=host -t ${REPOSITORY_IMAGE_BACKEND} .
    - docker push ${REPOSITORY_IMAGE_BACKEND}

deploy:
  tags:
    - kuber
  stage: deploy
  only:
    - develop
    - master
  image: roffe/kubectl:v1.13.2
  script:
    - NAMESPACE_NAME=$(echo -e gitdep-$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME | tr -d _)
    - CI_PROJECT_NAME=$(echo -e $CI_PROJECT_NAME | tr -d _)
    - HOSTNAME=$(echo -e $CI_PROJECT_PATH | tr '/' '-' | tr '_' '-')
    - sed -i -e "s@__NAMESPACE_NAME__@${NAMESPACE_NAME}@g" dp.yml
    - sed -i -e "s@__CI_PROJECT_NAME__@${CI_PROJECT_NAME}@g" dp.yml
    - sed -i -e "s@__REPOSITORY_IMAGE__@${REPOSITORY_IMAGE}@g" dp.yml
    - sed -i -e "s@__HOSTNAME__@${HOSTNAME}@g" dp.yml
    - kubectl config set-cluster test-cluster --server=$(kubectl describe services | grep IP | sed -E 's/IP:[[:space:]]+//' | sed -E 's/Type:[[:space:]]+//' | tr -d ClusterIP)
    - kubectl create secret -n "$NAMESPACE_NAME" docker-registry gitlab-registry --docker-server="$CI_REGISTRY" --docker-username="$REGISTRY_DEPLOY_LOGIN" --docker-password="$REGISTRY_DEPLOY_TOKEN" --docker-email="$GITLAB_USER_EMAIL" -o yaml --dry-run | kubectl replace -n "$NAMESPACE_NAME" --force -f -
    - kubectl apply -f dp.yml

backend:
  tags:
    - kuber
  stage: backend
  only:
    - develop
    - master
  image: roffe/kubectl:v1.13.2
  script:
    - NAMESPACE_NAME=$(echo -e gitdep-$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME | tr -d _)
    - CI_PROJECT_NAME=$(echo -e $CI_PROJECT_NAME | tr -d _)
    - HOSTNAME=$(echo -e $CI_PROJECT_PATH | tr '/' '-' | tr '_' '-')

    - kubectl config set-cluster test-cluster --server=$(kubectl describe services | grep IP | sed -E 's/IP:[[:space:]]+//' | sed -E 's/Type:[[:space:]]+//' | tr -d ClusterIP)
    - kubectl create secret -n "$NAMESPACE_NAME" docker-registry gitlab-registry --docker-server="$CI_REGISTRY" --docker-username="$REGISTRY_DEPLOY_LOGIN" --docker-password="$REGISTRY_DEPLOY_TOKEN" --docker-email="$GITLAB_USER_EMAIL" -o yaml --dry-run | kubectl replace -n "$NAMESPACE_NAME" --force -f -
    - sed -i -e "s@__NAMESPACE_NAME__@${NAMESPACE_NAME}@g" dp-node.yml
    - sed -i -e "s@__CI_PROJECT_NAME__@${CI_PROJECT_NAME}@g" dp-node.yml
    - sed -i -e "s@__REPOSITORY_IMAGE_BACKEND__@${REPOSITORY_IMAGE_BACKEND}@g" dp-node.yml
    - sed -i -e "s@__HOSTNAME__@${HOSTNAME}@g" dp-node.yml
    - kubectl apply -f dp-node.yml
